"""initial schema: agents, artifacts, agent_sessions

Revision ID: 7eafd694e27c
Revises:
Create Date: 2026-08-12 22:04:18.317313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7eafd694e27c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("session_id", sa.String(length=512), nullable=False),
        sa.Column("history", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index("ix_agent_sessions_updated_at", "agent_sessions", ["updated_at"], unique=False)
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("allowed_tools", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agents_owner_updated", "agents", ["owner_id", "updated_at"], unique=False)
    op.create_table(
        "artifact_access",
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("download_url", sa.Text(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("filename"),
    )
    op.create_index(
        "ix_artifact_access_user_created",
        "artifact_access",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "artifact_content",
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("filename"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artifact_content")
    op.drop_index("ix_artifact_access_user_created", table_name="artifact_access")
    op.drop_table("artifact_access")
    op.drop_index("ix_agents_owner_updated", table_name="agents")
    op.drop_table("agents")
    op.drop_index("ix_agent_sessions_updated_at", table_name="agent_sessions")
    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
