"""Safe, collision-free storage for files generated by agent tools."""

from __future__ import annotations

import os
import re
import unicodedata
from dataclasses import dataclass
from itertools import count
from pathlib import Path
from typing import Protocol
from urllib.parse import quote, unquote

from shared.types import ArtifactReference

ARTIFACTS_URL_PATH = "/artifacts"
_DEFAULT_ARTIFACTS_DIR = "artifacts"
_SAFE_FILENAME_CHARACTER = re.compile(r"[^\w. -]", flags=re.UNICODE)
_REPEATED_SEPARATOR = re.compile(r"[- ]{2,}")
_MAX_STEM_BYTES = 180


@dataclass(frozen=True)
class StoredArtifact:
    """A generated file's private storage path and public download metadata."""

    path: Path
    filename: str
    download_url: str


class ArtifactAccessRepository(Protocol):
    """Ownership manifest for generated files exposed through HTTP."""

    async def grant(self, user_id: str, artifacts: list[ArtifactReference]) -> None:
        """Associate generated artifacts with the authenticated user."""
        ...

    async def can_download(self, user_id: str, filename: str) -> bool:
        """Return whether this user owns the generated filename."""
        ...


def get_artifacts_directory() -> Path:
    """Return the configured artifact root, creating it when necessary.

    Relative ``ARTIFACTS_DIR`` values are resolved against the process's
    working directory, matching the rest of the app's local file settings.
    """
    directory = Path(os.getenv("ARTIFACTS_DIR", _DEFAULT_ARTIFACTS_DIR)).expanduser().resolve()
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _truncate_utf8(value: str, maximum_bytes: int) -> str:
    """Trim a filename stem without splitting a multi-byte character."""
    encoded = value.encode("utf-8")
    if len(encoded) <= maximum_bytes:
        return value
    return encoded[:maximum_bytes].decode("utf-8", errors="ignore")


def safe_artifact_filename(
    requested_filename: str | None,
    *,
    default_stem: str,
    extension: str,
) -> str:
    """Reduce an untrusted filename to a safe basename with a fixed extension.

    Directory components (POSIX or Windows), leading dots, control characters,
    and punctuation with special filesystem meaning are discarded or replaced.
    The caller owns ``extension``; the untrusted value can never change the
    generated file type.
    """
    if not extension.startswith(".") or len(extension) < 2:
        raise ValueError("extension must start with a dot and include a file type.")

    raw = unicodedata.normalize("NFKC", requested_filename or "")
    basename = raw.replace("\\", "/").rsplit("/", maxsplit=1)[-1]
    cleaned = _SAFE_FILENAME_CHARACTER.sub("-", basename)
    cleaned = _REPEATED_SEPARATOR.sub("-", cleaned).strip(" ._-")

    if cleaned.lower().endswith(extension.lower()):
        stem = cleaned[: -len(extension)]
    elif "." in cleaned:
        stem = cleaned.rsplit(".", maxsplit=1)[0]
    else:
        stem = cleaned

    stem = _truncate_utf8(stem.strip(" ._-"), _MAX_STEM_BYTES) or default_stem
    return f"{stem}{extension.lower()}"


def resolve_artifact_source(reference: str, *, extension: str) -> Path:
    """Resolve a generated-artifact URL, safe filename, or legacy absolute path.

    Artifact URLs and filenames are confined to ``ARTIFACTS_DIR``. Absolute
    paths remain supported for callers of the older tool contract, but only
    when they identify a readable, non-symlink regular file of the expected
    type. Relative paths with directories are rejected rather than resolved
    against the process working directory.
    """
    value = reference.strip()
    if not value:
        raise ValueError("Artifact source cannot be empty.")

    artifact_prefix = f"{ARTIFACTS_URL_PATH}/"
    if value.startswith(artifact_prefix):
        filename = unquote(value.removeprefix(artifact_prefix))
        expected_name = safe_artifact_filename(
            filename,
            default_stem="artifact",
            extension=extension,
        )
        if filename != expected_name:
            raise ValueError("Artifact URL must contain one safe filename of the expected type.")
        candidate = get_artifacts_directory() / filename
    else:
        supplied_path = Path(value)
        if supplied_path.is_absolute():
            candidate = supplied_path
        else:
            expected_name = safe_artifact_filename(
                value,
                default_stem="artifact",
                extension=extension,
            )
            if value != expected_name:
                raise ValueError("Artifact source must be a safe filename without directories.")
            candidate = get_artifacts_directory() / value

    if candidate.is_symlink():
        raise ValueError("Artifact source cannot be a symbolic link.")
    try:
        resolved = candidate.resolve(strict=True)
    except FileNotFoundError as exc:
        raise FileNotFoundError(f"Artifact source does not exist: {reference}") from exc
    if not resolved.is_file():
        raise ValueError("Artifact source must be a regular file.")
    if resolved.suffix.lower() != extension.lower():
        raise ValueError(f"Artifact source must be a {extension.lower()} file.")
    if not os.access(resolved, os.R_OK):
        raise PermissionError(f"Artifact source is not readable: {reference}")
    return resolved


def store_artifact_bytes(
    content: bytes,
    *,
    requested_filename: str | None,
    default_stem: str,
    extension: str,
) -> StoredArtifact:
    """Atomically store bytes under a unique, sanitized artifact filename."""
    directory = get_artifacts_directory()
    safe_name = safe_artifact_filename(
        requested_filename,
        default_stem=default_stem,
        extension=extension,
    )
    base = Path(safe_name)

    for collision_index in count(1):
        filename = (
            safe_name if collision_index == 1 else f"{base.stem}-{collision_index}{base.suffix}"
        )
        destination = directory / filename
        try:
            descriptor = os.open(
                destination,
                os.O_WRONLY | os.O_CREAT | os.O_EXCL,
                0o644,
            )
        except FileExistsError:
            continue

        try:
            with os.fdopen(descriptor, "wb") as artifact_file:
                artifact_file.write(content)
        except BaseException:
            destination.unlink(missing_ok=True)
            raise

        return StoredArtifact(
            path=destination,
            filename=filename,
            download_url=f"{ARTIFACTS_URL_PATH}/{quote(filename, safe='')}",
        )

    raise RuntimeError("Unable to allocate a unique artifact filename.")  # pragma: no cover


def store_artifact_text(
    content: str,
    *,
    requested_filename: str | None,
    default_stem: str,
    extension: str,
) -> StoredArtifact:
    """Encode UTF-8 text and store it through the same atomic byte path."""
    return store_artifact_bytes(
        content.encode("utf-8"),
        requested_filename=requested_filename,
        default_stem=default_stem,
        extension=extension,
    )
